version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: hangout
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: hangout
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3305:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql